/**
 * Created by HoangNH on 12/22/2016.
 */
import {InjectionToken} from '@angular/core';

export interface IPageId {
    NONE: number;

    // ------ CONFIG: 1 ------
    CONFIG: number;
    CONFIG_PAGE: number;
    CONFIG_CLIENT: number;
    CONFIG_TENANT: number;
    CONFIG_ROLE: number;
    CONFIG_ACCOUNT: number;
    CONFIG_WEBSITE: number;
    CONFIG_EMAIL: number;

    // ------ SURVEY: 100 ------
    SURVEY: number;
    SURVEY_LIST: number;
    SURVEY_NEWS: number;
    SURVEY_CATEGORY: number;
    SURVEY_QUESTION: number;
    SURVEY_GROUP_QUESTION: number;
    SURVEY_MY_SURVEY: number;
    SURVEY_REPORT: number;
    SURVEY_REPORT_LIST: number;
    SURVEY_REPORT_BY_USER: number;
    SURVEY_REPORT_DAY_DETAIL: number;
    SURVEY_NEWS_REFERENCE: number;
    SURVEY_NEWS_PREVIEW: number;
    SURVEY_NEWS_DETAIL: number;
    SURVEY_DASHBOARD: number;
    SURVEY_PREVIEW: number;
    SURVEY_QUESTION_APPROVE: number;

    // ------ WEBSITE: 200 ------
    WEBSITE: number;
    NEWS: number;
    NEWS_LIST: number;
    NEWS_CATEGORY: number;
    NEWS_SPECIALIST: number;
    NEWS_SERVICES: number;
    NEWS_RECRUITMENT: number;
    NEWS_ABOUT_US: number;
    NEWS_MEDICAL_KNOWLEDGE: number;
    WEBSITE_CONFIG: number;
    SLIDER: number;
    MENU: number;
    CUSTOMER: number;
    FEEDBACK: number;
    PROMOTION: number;
    FAQS: number;
    WEBSITE_COURSE: number;
    VIDEO: number;
    ALBUM: number;
    BANNER: number;
    FOLDER: number;

    // ------ HR: 300 ------
    HR: number;
    ORGANIZATION: number;
    TITLE: number;
    POSITION: number;
    USER: number;
    USER_LIST: number;
    LABOR_CONTRACT: number;
    INSURANCE: number;
    QUICK_INSERT_USER: number;
    OFFICE: number;
    OFFICE_POSITION: number;
    TRAINING_HISTORY: number;
    EMPLOYMENT_HISTORY: number;
    COMMENDATION_DISCIPLINE: number;
    USER_RECORDS_MANAGEMENT: number;
    MANAGER_CONFIG: number;
    ASSESSMENT: number;
    ASSESSMENT_APPROVE: number;
    CRITERIA_LIBRARY: number;
    CRITERIA_CONFIG: number;
    MY_ASSESSMENT: number;
    ASSESSMENT_RESULT: number;

    // ------ TASK: 400 ------
    TASK_GROUP: number;
    TASK: number;
    TASK_APPROVE: number;
    TASK_LIST: number;

    // ------ WEBSITE: 500 ------
    MAIL: number;
    MAIL_GROUP: number;
    WEBSITE_PROMOTION: number;

    // ------ CRM: 600 ------
    CUSTOMER_CARE: number;
    CUSTOMER_CARE_CONFIG_FEEDBACK: number;
    CUSTOMER_CARE_MINE: number;
    CUSTOMER_CARE_RESEARCH_DOCTOR: number;
    CUSTOMER_CARE_QUALITY_CONTROL: number;
    CUSTOMER_CARE_REPORT_BY_EMPLOYEE: number;
    CUSTOMER_CARE_CONFIG_MISS_INFORMATION: number;
    CUSTOMER_CARE_REPORT_NOT_GLAD: number;
    CUSTOMER_CARE_REPORT_ABNORMAL: number;
    CUSTOMER_CARE_REPORT_CUSTOMER_COMMENT: number;
    CUSTOMER_CARE_REPORT_MEDICAL_RECORD: number;
    CUSTOMER_CARE_CONFIG_CRITERIA: number;
    CUSTOMER_CARE_INSTRUCTION_CALL: number;
    CUSTOMER_CARE_REPORT_MARK_SCORE: number;
    CUSTOMER_CARE_COMPLAIN_CUSTOMER: number;
    CUSTOMER_CARE_REPORT_CAMPAIGN: number;
    CUSTOMER_CARE_REPORT_AFTER_REMINDER: number;

    // ------ TIMEKEEPING: 700 ------
    TIMEKEEPING_CONFIG: number;
    TIMEKEEPING_WORK_SCHEDULE: number;
    TIMEKEEPING_DAY_OFF_APPROVE: number;
    TIMEKEEPING_CONNECT_TO_MACHINE: number;
    TIMEKEEPING_WORKING_DAY_DATA: number;
    TIMEKEEPING_DOWNLOAD_USER_DATA: number;
    TIMEKEEPING_UPLOAD_USER_DATA: number;
    TIMEKEEPING_SYNC_DATA: number;
    TIMEKEEPING_TIMESHEET: number;
    TIMEKEEPING_IN_LATE_OUT_EARLY: number;
    TIMEKEEPING_OVERTIME: number;
    TIMEKEEPING_FORGOT_CHECK_IN: number;
    TIMEKEEPING_IN_LATE_OUT_EARLY_FREQUENTLY: number;

    // ----- PATIENT: 800 -----
    PATIENT: number;
    CONFIG_JOB: number;
    CONFIG_PATIENT_SOURCE: number;
    CONFIG_PATIENT_SUBJECT: number;
    LIST_PATIENT: number;

    // ----- EVENTS: 10000 -----
    EVENT: number;
    EVENT_LIST: number;

    // ---- Brand: 20000 ------
    BRAND: number;

    // ---- PRODUCT ---
    PRODUCT_MANAGER: number;
    PRODUCT: number;
    // PRODUCT_ATTRIBUTE: number;
    PRODUCT_CATEGORY: number;
    // SUPPLIER: number;
    // UNIT: number;
    // ----- WAREHOUSE: 100000 -----
    // WAREHOUSE: number;
    // PRODUCT: number;
    // PRODUCT_ATTRIBUTE: number;
    // PRODUCT_CATEGORY: number;
    // SUPPLIER: number;
    // BRANDS: number;
    // UNIT: number;
    // WAREHOUSE_MANAGEMENT: number;
    // GOODS_RECEIPT_NOTE: number;
    // GOODS_DELIVERY_NOTE: number;
    // WAREHOUSE_CONFIG: number;
    // INVENTORY: number;
    // INVENTORY_REPORT: number;
}

export const PAGE_ID_DI: IPageId = {
    NONE: -1,

    // ------ CONFIG: 1 ------
    CONFIG: 1,
    CONFIG_PAGE: 2,
    CONFIG_ROLE: 3,
    CONFIG_CLIENT: 4,
    CONFIG_TENANT: 5,
    CONFIG_ACCOUNT: 6,
    CONFIG_WEBSITE: 8,
    CONFIG_EMAIL: 9,

    // ------ SURVEY: 100 ------
    SURVEY: 100,
    SURVEY_LIST: 101,
    SURVEY_NEWS: 114,
    SURVEY_CATEGORY: 102,
    SURVEY_QUESTION: 103,
    SURVEY_GROUP_QUESTION: 104,
    SURVEY_MY_SURVEY: 105,
    SURVEY_REPORT: 106,
    SURVEY_REPORT_LIST: 107,
    SURVEY_REPORT_BY_USER: 108,
    SURVEY_REPORT_DAY_DETAIL: 109,
    SURVEY_NEWS_REFERENCE: 110,
    SURVEY_NEWS_PREVIEW: 111,
    SURVEY_NEWS_DETAIL: 112,
    SURVEY_DASHBOARD: 112,
    SURVEY_PREVIEW: 113,
    SURVEY_QUESTION_APPROVE: 114,

    // ------ WEBSITE: 200 ------
    WEBSITE: 200,
    NEWS: 201,
    NEWS_LIST: 220,
    NEWS_CATEGORY: 202,
    NEWS_SPECIALIST: 203,
    NEWS_SERVICES: 204,
    NEWS_RECRUITMENT: 205,
    NEWS_ABOUT_US: 206,
    NEWS_MEDICAL_KNOWLEDGE: 207,
    WEBSITE_CONFIG: 208,
    SLIDER: 209,
    MENU: 210,
    CUSTOMER: 211,
    FEEDBACK: 212,
    PROMOTION: 213,
    FAQS: 214,
    WEBSITE_COURSE: 215,
    VIDEO: 216,
    ALBUM: 227,
    BANNER: 219,
    FOLDER: 217,

    // ------ HR: 300 ------
    HR: 300,
    ORGANIZATION: 321,
    TITLE: 301,
    POSITION: 302,
    USER: 303,
    USER_LIST: 304,
    LABOR_CONTRACT: 305,
    INSURANCE: 306,
    QUICK_INSERT_USER: 307,
    OFFICE: 308,
    OFFICE_POSITION: 309,
    TRAINING_HISTORY: 310,
    EMPLOYMENT_HISTORY: 311,
    COMMENDATION_DISCIPLINE: 312,
    USER_RECORDS_MANAGEMENT: 313,
    MANAGER_CONFIG: 314,
    ASSESSMENT: 315,
    ASSESSMENT_APPROVE: 316,
    CRITERIA_LIBRARY: 317,
    CRITERIA_CONFIG: 318,
    MY_ASSESSMENT: 319,
    ASSESSMENT_RESULT: 320,

    // ------ TASK: 400 ------
    TASK: 400,
    TASK_GROUP: 401,
    TASK_APPROVE: 402,
    TASK_LIST: 403,

    // ------ WEBSITE: 500 ------
    MAIL: 500,
    MAIL_GROUP: 501,
    WEBSITE_PROMOTION: 502,

    // ------ CRM: 600 ------
    CUSTOMER_CARE: 600,
    CUSTOMER_CARE_CONFIG_FEEDBACK: 601,
    CUSTOMER_CARE_MINE: 602,
    CUSTOMER_CARE_RESEARCH_DOCTOR: 603,
    CUSTOMER_CARE_QUALITY_CONTROL: 604,
    CUSTOMER_CARE_REPORT_BY_EMPLOYEE: 605,
    CUSTOMER_CARE_CONFIG_MISS_INFORMATION: 606,
    CUSTOMER_CARE_REPORT_NOT_GLAD: 607,
    CUSTOMER_CARE_REPORT_ABNORMAL: 608,
    CUSTOMER_CARE_REPORT_CUSTOMER_COMMENT: 609,
    CUSTOMER_CARE_REPORT_MEDICAL_RECORD: 610,
    CUSTOMER_CARE_CONFIG_CRITERIA: 611,
    CUSTOMER_CARE_INSTRUCTION_CALL: 612,
    CUSTOMER_CARE_REPORT_MARK_SCORE: 613,
    CUSTOMER_CARE_COMPLAIN_CUSTOMER: 614,
    CUSTOMER_CARE_REPORT_CAMPAIGN: 615,
    CUSTOMER_CARE_REPORT_AFTER_REMINDER: 616,

    // ------ TIMEKEEPING: 700 ------
    TIMEKEEPING_CONFIG: 700,
    TIMEKEEPING_WORK_SCHEDULE: 701,
    TIMEKEEPING_DAY_OFF_APPROVE: 702,
    TIMEKEEPING_CONNECT_TO_MACHINE: 703,
    TIMEKEEPING_WORKING_DAY_DATA: 704,
    TIMEKEEPING_DOWNLOAD_USER_DATA: 705,
    TIMEKEEPING_UPLOAD_USER_DATA: 706,
    TIMEKEEPING_SYNC_DATA: 707,
    TIMEKEEPING_TIMESHEET: 708,
    TIMEKEEPING_IN_LATE_OUT_EARLY: 790,
    TIMEKEEPING_OVERTIME: 710,
    TIMEKEEPING_FORGOT_CHECK_IN: 711,
    TIMEKEEPING_IN_LATE_OUT_EARLY_FREQUENTLY: 712,

    // ----- PATIENT:  800 ------
    PATIENT: 800,
    CONFIG_JOB: 801,
    CONFIG_PATIENT_SOURCE: 802,
    CONFIG_PATIENT_SUBJECT: 803,
    LIST_PATIENT: 804,

    // ----- EVENTS: 10000 -----
    EVENT: 10000,
    EVENT_LIST: 10001,

    // ------ BRAND: 20000 -----
    BRAND: 20000,

    // ----- PRODUCT ----
    PRODUCT_MANAGER: 30000,
    PRODUCT: 30001,
    // PRODUCT_ATTRIBUTE: 30002,
    PRODUCT_CATEGORY: 30002,
    // SUPPLIER: 30004,
    // UNIT: 30007,
    // ----- WAREHOUSE: 100000 -----
    // WAREHOUSE: 100000,
    // PRODUCT: 100001,
    // PRODUCT_ATTRIBUTE: 100002,
    // PRODUCT_CATEGORY: 100003,
    // SUPPLIER: 100004,
    // BRANDS: 100006,
    // UNIT: 100007,
    // WAREHOUSE_MANAGEMENT: 100009,
    // GOODS_RECEIPT_NOTE: 100010,
    // GOODS_DELIVERY_NOTE: 100011,
    // WAREHOUSE_CONFIG: 100012,
    // INVENTORY: 100015,
    // INVENTORY_REPORT: 100013
};

// Injection Tokens
export let PAGE_ID = new InjectionToken<IPageId>('page.config');
